### PR TITLE
Add strlcpy

### PR DESCRIPTION
**Pull request by MBeijer**

### CODE REVIEW

**Comment by bebbo** [comment]
```
size_t
strlcpy(char *dst, const char *src, size_t dsize) {
    const char * p = src;
    if (dsize) {
      while (dsize--) {
        if ((*dst++ = *p++) == 0)
            break;
      } 
      dst[-1] = 0;
    }

    while (*p)
        ++p;

    return p - src;
}
```

**Comment by MBeijer** [comment]
I was unsure where to put it, in sources/nix, sources/nix13 + sources/nix20, or all of them? I'll update with your version

**Comment by bebbo** [comment]
one file in `nix/string` please - there is no difference for 1.3/2.0+

**Comment by MBeijer** [comment]
Done

**Pull request merged**
